services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-}
      secrets:
        - github_token
        - email
    environment:
      APP_VERSION: ${APP_VERSION:-}
    ports:
      - "8080:80"

secrets:
  github_token:
    environment: GITHUB_TOKEN
  email:
    environment: EMAIL
