services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token
        - email
    ports:
      - "8080:80"

secrets:
  github_token:
    environment: GITHUB_TOKEN
  email:
    environment: EMAIL
